version: "2"
services:
    web:
        build: ./SampleCoreApp3 
        container_name: samplecoreapp3-web
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        container_name: samplecoreapp3-back
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Password01"
            ACCEPT_EULA: "Y"
