version: "2"
services:
    web:
#        build: ./SampleCoreApp3
        image: "acraksdemo.azurecr.io/samplecoreapp3-web:mssql-v1" 
        container_name: samplecoreapp3-web
        ports:
            - "80:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        container_name: samplecoreapp3-back
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Password01"
            ACCEPT_EULA: "Y"
